### PR TITLE
Py2 + Py3 polyglot for RelStorage 1.6.0b2

### PR DESCRIPTION
**Pull request by ztane**
This is not right now automatically mergeable since the RelStorage has diverged a bit, but I've been using this successfully since the last commit for several Pyramid-based Python 3 ZODB applications.

### CODE REVIEW

**Comment by fgregg** [comment]
I am interested in getting python 3 support. If I worked on this would there be anyone to review the PR?

**Comment by jamadden** [comment]
Now that we have CI in place, I plan to start on this fairly soon. 

I sincerely appreciate all the work put in to this PR! However, the next release of RelStorage will have an updated ZODB dependency that has dropped support for anything less than Python 2.6 or 3.3, so there's little point in RelStorage supporting other versions. That simplifies porting quite a bit and leads to a somewhat different porting strategy. It will probably be simplest to start from scratch, but this PR will serve as a valuable reference.

**Comment by jamadden** [comment]
Moved to #55.

Thanks again for this work.

**Comment by ztane** [comment]
Nice, I am going to try out the new Relstorage right away

**Comment by jamadden** [comment]
2.0b1 has been released with these changes.

**Pull request closed without merging**
