### PR TITLE
Small warning note on cache settings when using SQLite as a backend

### PR DESCRIPTION
**Pull request by pfw**

### CODE REVIEW

**Comment by jamadden** [comment]
Thanks for the contribution! 

This is already documented in the sqlite-specific documentation (https://relstorage.readthedocs.io/en/latest/sqlite3/options.html), which is required reading for using the sqlite storage. Each cross-reference adds to the future maintenance burden, so there's a tradeoff in adding them. Can you explain why you think this one is necessary?

**Comment by pfw** [comment]
Ah yes I see that now. I was looking through the source for any mention of cache-local-dir exactly so didn't find it. Maybe it makes more sense to just have a note in the "SQLite Adapter Options" page in:

```
Using a persistent cache file is not supported with this driver and will be automatically disabled. In some cases, it may be advantageous to also disable RelStorage’s in-memory pickle cache altogether (cache-local-mb 0) and allow the operating system’s filesystem cache to serve that purpose.
```

Just enough so that a search of the docs for the exact setting shows this section.

**Comment by jamadden** [comment]
Makes sense to me!

**Comment by pfw** [comment]
I've made a change for that in this pull request.

**Comment by jamadden** [comment]
Thanks!

**Pull request merged**
