### PR TITLE
Fix zodbconvert --incremental option

### PR DESCRIPTION
**Pull request by thefunny42**
Would it be possible to get a beta release with this fix included ?

### CODE REVIEW

**Comment by mamico** [comment]
@hathawsh any feedback about this proposal? thanks

**Comment by peterjacobs** [comment]
it is a great fix!

confirmed working with Oracle 11:
zodbconvert relstorage -> filestorage
make a change in the Plone site
zodbconvert --incremental relstorage -> filestorage
zodbconvert --clear filestorage -> relstorage
check everything is working

**Comment by jamadden** [comment]
It would be great to have functional test cases for this. I'm not sure what the test situation is like for the standalone zodbconvert command, though. 

Ref #32

**Comment by jamadden** [comment]
There are the start of tests in `relstorage/tests/test_zodbconvert.py`. These are now being run via CI and have code coverage reported on coveralls.io. 

The downside is that they only cover FileStorage, so they need some extensions (in reltestbase?) to do some copying with RDBMS, I suspect.

**Pull request closed without merging**
