### PR TITLE
Performance work, especially on PostgreSQL

### PR DESCRIPTION
**Pull request by jamadden**
Big boosts on PostgreSQL 9.5 and later: conservatively up to 40% on reads and 25% on writes. Most of the read performance exists for older versions, but the write gains are much more limited.

This wound up incorporating a couple different avenues:

- UPSERTS for postgresql 9.5+. Biggest write gains came here.
- prepared statements for reading (#148)

   I've gone over the statements exercised by the benchmarks and plucked all the low hanging fruit. In the "standard" benchmark, there are 120,303 "load current" calls, by far the most numerous by orders of magnitude.  Writing objects was already batched and didn't have a lot of room to improve. 

  MySQL is being uncooperative when it comes to this approach (#155).  However, once #156 lands we'll have a driver that supports the binary prepared statements and we can revisit the issue for "load current" then.

- Some code optimizations.

There's quite a few refactorings and cleanups included in this.

### CODE REVIEW

**Comment by jimfulton** [comment]
Interesting. I played with upserts for the newt table and didn't see a win, but perhaps it got lost in the noise.

**Comment by jamadden** [comment]
The win here was that if we weren't able to do an upsert, every INSERT had to be preceded by a DELETE. So the upsert lets us reduce the queries by half.

**Comment by jimfulton** [comment]
I get that, I just didn't see it when doing the same dance on the ``newt`` table. <shrug>  This was going against a local Postscript server on my Mac.  I was only looking at history-free storage.  I imagine the benefit would be greater talking to a non-local server.

**Comment by jamadden** [comment]
This was also a local 9.6 server testing history-free storage. The win was very apparent across repeated tests.

I oversimplified the explanation somewhat. This all goes through the RowBatcher class, so the DELETE statement winds up being dynamically generated and looks like 'DELETE FROM object_state WHERE zoid IN (123456, 789456, 456789, 456789, 4579846)'. Perhaps that's just a tough query to parse and plan (it seems that postgres is relatively slow at parsing and planning, hence the big win for prepared statements). Of course the upsert is also dynamically generated in the same way, but it doesn't have any explicit WHERE clauses like that.

**Comment by jimfulton** [comment]
That's interesting. I wonder if this changed.  In my checkout, 3e2acd8d30554b1f1710f08ffcdf61c4f542d03a, I see:


    def _move_from_temp_object_state(self, cursor, tid):
        """
        Called for history-free databases.

        Should replace all entries in object_state with the
        same zoid from temp_store.
        """

        stmt = """
        DELETE FROM object_state
        WHERE zoid IN (SELECT zoid FROM temp_store)
        """
        cursor.execute(stmt)

        stmt = self._move_from_temp_hf_insert_query
        cursor.execute(stmt, (tid,))

That's what I'm doing for the ``newt`` table as well.  (I'll probably have to keep doing that way for semantic reasons.)

**Comment by jamadden** [comment]
Ah, this is the step before that, where objects are initially written *into* `temp_store` via `_generic_store_temp`.

Now why or how exactly you could end up with a primary key violation writing one transactions worth of objects into `temp_store` I don't know. Shouldn't ZODB be providing each object only once? That is, calling `store()` only once per object? But I didn't investigate why that was allowed for...maybe something to do with savepoints? Dunno. I just made the existing structure faster 😄 

The `_move_from_temp` step I didn't look at at all, it didn't show up as a hot spot.

**Comment by jimfulton** [comment]
Ah, OK. Yeah, it might be nice if ZODB avoided these dups.  It's been an issue for a long time (possibly forever :-)).  But conflict resolution could produce dups as well.

**Comment by jamadden** [comment]
> But conflict resolution could produce dups as well.

Ahh, that makes sense. Thanks.

**Comment by jimfulton** [comment]
WRT object and transaction sizes, I find ~1k for object sizes to be more in line with my experience.  I've also tended to see much smaller transaction sizes.  IIUC, shootout defaults to 1000 objects due to a oddity in implementation that's since been fixed. In my experience, transaction sizes for databases without catalogs were 10 or less and even with catalogs, transaction sizes were ~100.

With the default object sizes, the data attributes were empty strings, which made impact of full-text indexes hard to gauge.  :-).

**Comment by jamadden** [comment]
[I looked at one of our production databases](https://github.com/zodb/relstorage/issues/156#issuecomment-274671276) and found average size to be 244 with stddev of 392. Those are compressed by zc.zlibstorage, and we do use catalogs, so those probably line up roughly with your experience. I didn't think to try to bucket by tid to get transaction sizes. Maybe I can do that this weekend.

**Comment by jimfulton** [comment]
Also, wrt speedups, poll_invalidations makes multiple queries (2 or 3; BTW, I'm +1 for removing that extra block of code) when there are updates.

Why not simply call (the prepared version of):

                SELECT zoid, tid
                FROM object_state
                WHERE tid > %(tid)s

(or the equiv for HP)?

Surely this isn't any more expensive than:

    SELECT MAX(tid) FROM transaction

when there are no updates and avoids an extra round trip when there are.

**Comment by jamadden** [comment]
I agree, now that invalidation polling is no longer optional that entire system can be rethought.

**Comment by jamadden** [comment]
> But now that I'm thinking about it, maybe I'll give it a try just for my own curiosity.

Silly me, I already did that and included it in one of the commits. 

Measured on its own with zodbshootout defaults against a local HF server for add/update I get an improvement around 2%. Measurable, but small enough to be within the noise.

However, if I drop the transaction size from 1000 to 100, then the difference goes to ~25% for add and up to 50% for update! Clearly every query counts. The bigger difference in update makes sense because the DELETE statement would have more work to do (that would get combined into a single INSERT)...it makes me wonder if this could also increase storage efficiency, if table space is able to be reused.

For comparison, here's the numbers from 'zodbshootout -c2 -n 100 --test-reps 200' (so the total amount of objects written is the same) from 2.0:
```
"Transaction",               postgresql_hf
"Add 100 Objects",                    8090
"Update 100 Objects",                 4942
"Read 100 Warm Objects",              6747
"Read 100 Cold Objects",             11519
"Read 100 Hot Objects",              53551
```

And here it is with master:
```
"Transaction",               postgresql_hf
"Add 100 Objects",                   13265
"Update 100 Objects",                 8779
"Read 100 Warm Objects",              6935
"Read 100 Cold Objects",             14379
"Read 100 Hot Objects",              53300
```

Much better! Improvements of 60%, 75%, and 25% in the tests that have substantial differences.

**Comment by jamadden** [comment]
> I didn't think to try to bucket by tid to get transaction sizes. Maybe I can do that this weekend.

On that same production database with 18.6 million objects and 7,836,143 transactions, the average transaction size is 2.4 with a standard deviation of 123. The maximum transaction is an impressive 262,871 objects.

**Comment by jimfulton** [comment]
With that sort of distribution the median would be more interesting.  Ditto for geometric mean, which is a little easier to compute.

**Comment by jamadden** [comment]
I agree, but MySQL has no `median` or `mean` function (as I found out). I was operating in the actual production environment so I didn't want to try any of the SQL-based solutions, they all seem to have terrible runtime characteristics. Next time I get access to a replica I can try something better.

**Comment by jimfulton** [comment]
Any idea when this will be released? I know of folks who would really benefit from it.

**Comment by jamadden** [comment]
I was hoping to look into #161 and #159 and merge #162 first. I suppose since it's going to be 1.2a1 the first two could wait for 1.2a2.

**Comment by jimfulton** [comment]
1.2? I'm confused. I would think 2.1.

Smaller releases get value in people's hands hands quicker.

Why not 2.1 now with the speed gains you already have and some other release(s) later?

**Comment by jamadden** [comment]
Yes, 2.1. Transposition typo.

RelStorage is critical infrastructure, I believe there need to be pre-releases for testing before automatic wide distribution. There are definitely changes here that have the potential to be disruptive/cause issues. Certainly my group will test it as best we can during pre-release.

I've been criticized for releasing gevent 1.2 "too soon" (8 months) after 1.1, despite the pre-releases. People like their core software unchanging, apparently---except of course when there's a bug that affects them, and then they'd like that bugfix, and only that bugfix, to be in a new release. I'd like to find a happy medium.

**Comment by jimfulton** [comment]
Well, prereleases don't require releases to be larger.  Larger releases increase the risk which causes release tempo to decrease, which makes releases larger, which ...

Seriously, if people want their software to be unchanging, they should pin their damn versions. :)

My recommendation, fwiw, is to make a 2.1 release branch and release a beta from it and only make bug fixes on it until it's final.

In the mean time, you could keep adding new things to master.

**Pull request merged**
