### PR TITLE
commit-lock-timeout support for PostgreSQL 9.3+

### PR DESCRIPTION
**Pull request by seanupton**
This commit-lock-timeout support for PostgreSQL 9.3+ should be backward-compatible with previous PostgreSQL versions.  The lock_timeout feature [1] in 9.3 is used, if version is 9.3 or greater.

[1] http://www.postgresql.org/docs/9.3/static/runtime-config-client.html

### CODE REVIEW

**Comment by jamadden** [comment]
It would be great to get this rebased and mergable. We have CI running now, but we're using the default version of Postgres, which is 9.1; that can be changed though.

**Comment by jamadden** [comment]
@seanupton Have you signed the Zope Contributor Agreement? That may be required to accept this patch (I'm not completely sure yet).

**Comment by seanupton** [comment]
@jamadden I have not signed ZF contributor agreement, but can if needed.  I am unclear on if RelStorage copyright was (wholly) assigned to ZF or in part owned by @hathawsh (and contributors)?

**Comment by jamadden** [comment]
As I understand it, plans are underway to transfer the repository to the zopefoundation organization. It's not totally clear yet where copyright and committer agreements are going to wind up, but I'm guessing that they will wind up being required.

**Comment by jamadden** [comment]
After a bit of back-and-forth with other committers, I think we're probably okay without a contributor agreement on this. 

Let me see how CI looks.

**Comment by jamadden** [comment]
CI looks good, new lines are covered and I've verified that we're running on Postgres 9.3 (which only adds about 5 seconds to the container startup). I'll merge this. Thanks!

**Pull request closed without merging**
